# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
name: Default
demands : vm

stages:
  - stage: Build
    jobs:
      - job: Build Job
        steps:
        - task: CopyFiles@2
          displayName: Copy Files 
          inputs:
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          displayName: Publish Build Artifacts 
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
  - stage: Deploy
    jobs:
      - job: Deploy Job
        steps:
        - task: DownloadBuildArtifacts@1
          displayName: Download Build Artifacts
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: TerraformInstaller@0
          displayName: Terraform Install
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV3@3
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Azure subscription 1(9aa4ae07-bc4b-487a-8473-faabe110ce6d)'
            backendAzureRmResourceGroupName: 'RG1'
            backendAzureRmStorageAccountName: 'tfstatestrg'
            backendAzureRmContainerName: 'tfstatecontainer'
            backendAzureRmKey: 'brstate.tfstate'
        - task: TerraformTaskV3@3
          displayName: Terraform Plan 
          inputs:
            provider: 'azurerm'
            command: 'plan'
        - task: TerraformTaskV3@3
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'Azure subscription 1(1)(9aa4ae07-bc4b-487a-8473-faabe110ce6d)'

